title: Creattive Web Blog - Bruno Xavier
email: contato@creattiveweb.com.br
description: "Artigos e dicas sobre Desenvolvimento Web, com foco em Front End e estrategias de Marketing."
url: "http://brunoxavierweb.github.io/blog"
github_username:  brunoxavierweb

# Build settings
markdown: kramdown
permalink: /:title/

gems:
  - jekyll-sitemap

css_folder:  "/assets/css"
js_folder:  "blog/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed
